// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinanzCSU.Models;

[Table("Category")]
public partial class Category
{
    [Key]
    public int CategoryID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<MonthlyAllocation> MonthlyAllocations { get; set; } = new List<MonthlyAllocation>();

    [InverseProperty("Category")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}