// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinanzCSU.Models;

[Table("Category")]
public partial class Category
{
    [StringLength(50)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    public int? BudgetID { get; set; }

    [Key]
    public int CategoryID { get; set; }
}