// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinanzCSU.Models;

[Table("MonthlyAllocation")]
public partial class MonthlyAllocation
{
    [Key]
    public int AllocationID { get; set; }

    public int? CategoryID { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? MonthAllocation { get; set; }

    public int? MonthID { get; set; }
}