// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FinanzCSU.Models;

public partial class Team106DBContext : DbContext
{
    public Team106DBContext()
    {
    }

    public Team106DBContext(DbContextOptions<Team106DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<MonthlyAllocation> MonthlyAllocations { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<UserBudget> UserBudgets { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=BUSCISSQL1901\\CISWEB;Initial Catalog=Team106DB;Persist Security Info=True;User ID=javan;Password=script");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryID).HasName("PK__Category__1908C5D9118A11CA");
        });

        modelBuilder.Entity<MonthlyAllocation>(entity =>
        {
            entity.HasKey(e => e.AllocationID).HasName("PK__MonthlyA__B3C6D6AB385204F8");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionID).HasName("PK__Transact__55433A4BC0FBA3F8");
        });

        modelBuilder.Entity<UserBudget>(entity =>
        {
            entity.HasKey(e => e.BudgetID).HasName("PK__UserBudg__E38E79C4473E5E7D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}