// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinanzCSU.Models;

public partial class Transaction
{
    [Key]
    public int TransactionID { get; set; }

    public int? MonthID { get; set; }

    public int? BudgetID { get; set; }

    public int? CategoryID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? TransactionAmount { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Memo { get; set; }
}