// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinanzCSU.Models;

[Table("UserBudget")]
public partial class UserBudget
{
    [Key]
    public int AllocationID { get; set; }
    public int CategoryID { get; set; }
    public int MonthID { get; set; }
    public int Allocation { get; set; }

    public int UserBudgetID { get; set; }

    public int BudgetID { get; set; }

    public int UserID { get; set; }

    [InverseProperty("UserBudget")]
    public virtual ICollection<MonthlyAllocation> MonthlyAllocations { get; set; } = new List<MonthlyAllocation>();

    [InverseProperty("UserBudget")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    [ForeignKey("UserID")]
    [InverseProperty("UserBudgets")]
    public virtual LoginInfo User { get; set; }
}